### ISSUE TITLE
Database error during installation

### ISSUE THREAD

**Issue by Mixxey** [matfish2/craft-optimum#6]
Hi there :slightly_smiling_face: 

I tried to install Optimum on Craft Pro 4.6.0 with MySQL 5.7.44

During installation I get the following error:

```
*** installing optimum
    > create table {{%optimum_experiments}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dateUpdated'
The SQL being executed was: CREATE TABLE optimum_experiments (
        id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name varchar(255) NOT NULL UNIQUE,
        handle varchar(255) NOT NULL UNIQUE,
        startAt datetime(0) NULL DEFAULT NULL,
        endAt datetime(0) NULL DEFAULT NULL,
        enabled tinyint(1) DEFAULT FALSE,
        dateCreated timestamp(0),
        dateUpdated timestamp(0)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/www-root/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /www-root/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE o...') #1 /www-root/vendor/yiisoft/yii2/db/Command.php(1102): yii\\db\\Command->internalExecute('CREATE TABLE o...')
#2 /www-root/vendor/yiisoft/yii2/db/Migration.php(322): yii\db\Command->execute()
#3 /www-root/vendor/matfish/craft-optimum/src/migrations/Install.php(23): yii\db\Migration->createTable('{{%optimum_expe...', Array)
#4 /www-root/vendor/craftcms/cms/src/db/Migration.php(49): matfish\Optimum\migrations\Install->safeUp()
#5 /www-root/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /www-root/vendor/craftcms/cms/src/base/Plugin.php(144): craft\db\MigrationManager->migrateUp(Object(matfish\Optimum\migrations\Install))
#7 /www-root/vendor/craftcms/cms/src/services/Plugins.php(533): craft\base\Plugin->install()
#8 /www-root/vendor/craftcms/cms/src/console/controllers/PluginController.php(281): craft\services\Plugins->installPlugin('optimum')
#9 /www-root/vendor/craftcms/cms/src/console/controllers/PluginController.php(143): craft\console\controllers\PluginController->_installPluginByHandle('optimum')
#10 [internal function]: craft\console\controllers\PluginController->actionInstall('optimum')
#11 /www-root/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /www-root/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /www-root/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('install', Array)
#14 /www-root/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('install', Array)
#15 /www-root/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('install', Array)
#16 /www-root/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('install', Array)
#17 /www-root/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('plugin/install', Array)
#18 /www-root/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('plugin/install', Array)
#19 /www-root/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('plugin/install', Array)
#20 /www-root/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /www-root/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#22 /www-root/craft(22): yii\base\Application->run()
#23 {main}
*** failed to install optimum: An error occurred while executing the "matfish\Optimum\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dateUpdated'
The SQL being executed was: CREATE TABLE optimum_experiments (
        id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name varchar(255) NOT NULL UNIQUE,
        handle varchar(255) NOT NULL UNIQUE,
        startAt datetime(0) NULL DEFAULT NULL,
        endAt datetime(0) NULL DEFAULT NULL,
        enabled tinyint(1) DEFAULT FALSE,
        dateCreated timestamp(0),
        dateUpdated timestamp(0)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8
```

Sadly, while I get along with my day-to-day frontend stuff well enough, this is sort of "too techie" for me to debug and I wasn't able to figure out if it is something I can fix on my own.

So any beginner-friendly advice about a solution would be very much appreciated :smile: 

Many thanks in advance!

**Comment by matfish2** [comment]
Hi, thanks for reporting.
Seems to be related to:
https://github.com/matfish2/craft-optimum/issues/3
Only there the issue was with `enabled` column.
Strange, as I've been using Craft's own method in the migration:
```
 'dateCreated' => $this->timestamp(),
  'dateUpdated' => $this->timestamp()
```
I'll look into it and revert shortly

**Comment by Mixxey** [comment]
Hey, thanks for getting back to me so quickly!

With a little help from my friend ChatGPT managed to debug it after all, I think :) I will open a pull request with my changes for you to look into.

**Comment by matfish2** [comment]
> I tried to install Optimum on Craft Pro 4.6.0 with MySQL 5.7.44

Seems like your MySQL version doesn't match the minimum requirement for Craft 4, which is  5.7.8+
https://craftcms.com/docs/4.x/requirements.html

**Comment by Mixxey** [comment]
Oh that is interesting! Thanks for the hint! I will look into that, too!

**Comment by matfish2** [comment]
Please let me know if that resolved the issue, as I am loath to make changes to accommodate unsupported versions.

**Comment by Mixxey** [comment]
Sure thing, I will get back to you once I tried that :)

**Comment by Mixxey** [comment]
I talked to our CTO and he pointed out that .44 is higher than .8, so our version of MySQL does meet the requirement. He assumes that there is a problem with your migration and also maybe a conflict with our MySQL strict mode settings (NO_ZERO_DATE)

I hope that helps :) 

Apart from that, I got your plugin to run on a test branch with my altered version and I really like what it does! :) Just need to figure out how to make use of it in GA4.

**Comment by matfish2** [comment]
> I talked to our CTO and he pointed out that .44 is higher than .8, 

Thanks! I read as 4.4 instead of 44 :)

> a problem with your migration and also maybe a conflict with our MySQL strict mode settings (NO_ZERO_DATE)

Ok, I'll look into it 

> Apart from that, I got your plugin to run on a test branch with my altered version and I really like what it does! :) Just need to figure out how to make use of it in GA4.

https://github.com/matfish2/craft-optimum?tab=readme-ov-file#4-set-a-custom-dimension-in-ga4
Please let me know if you need assistance.

**Comment by Mixxey** [comment]
Oh, thanks, that is very kind of you! :)

Well, I set up a custom dimension and tried to use it as a sort of filter for events, but as of now, I don't see anything in GA4. BUT of course that can be due to GA4's typical delay or because we didn't generate enough data yet (I just implemented a test on a staging branch). So we will look into that from time to time and try to generate some more data.

**Comment by matfish2** [comment]
> because we didn't generate enough data yet
Yes, it will only display results once you have enough data.
I'd also recommend inspecting the HTML to make sure the script for triggering the event is indeed called (or if you develop locally use a dummy `gtag` function https://github.com/matfish2/craft-optimum?tab=readme-ov-file#local-development).

**Comment by matfish2** [comment]
I've looked into Craft's native migrations and apparently they use:
`dateTime()->notNull()` rather than `timestamp()`
Fixed on version 1.3.0. Would appreciate if you can confirm this resolve the original issue.

**Comment by Mixxey** [comment]
Yes, everything works fine now! Great :) Thanks a lot for your support!
